Description: >
  Devops Cloud Engineer / Deepak
  It will create 2 hosts for managing EKS Cluster.

Parameters:
  EnvironmentName:
    Description: The environment name will be mapped to the resources.
    Default: devops-cloud-engineer-deep
    Type: String
  KeyPairName:
    Description: Key Pair will be used for the access to resource.
    Default: capstone
    Type: String
  amiImageId:
    Description: This refers to ami id of the image.
    Default: ami-05fa00d4c63e32376
    Type: String

Resources:
  SecurityGroupInstance:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName}-management-sec-grp
      GroupDescription: Port 22 will be used for security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  managerHost1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: SecurityGroupInstance
      KeyName: !Ref KeyPairName
      ImageId: !Ref amiImageId
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-manager1
        - Key: Project
          Value: !Ref EnvironmentName

  managerHost2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: SecurityGroupInstance
      KeyName: !Ref KeyPairName
      ImageId: !Ref amiImageId
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-manager2
        - Key: Project
          Value: !Ref EnvironmentName
