---
- name: "Download kubectl using curl"
  shell: curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl
  args:
    chdir: $HOME

- name: "Applying permissions to the binary"
  shell: chmod +x ./kubectl
  args:
    chdir: $HOME

- name: "Copy the kubectl binary to a folder as well as System Variable PATH"
  shell: mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
  args:
    chdir: $HOME

- name: "Add the $HOME/bin path to .bashrc file"
  shell: echo 'export PATH=$PATH:$HOME/bin' >> .bashrc
  args:
    chdir: $HOME
