---
- name: "Configuration of Amazon EKS with kubectl"
  hosts: manager[0]
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
  roles:
    - devops-cloud-engineer-deployment
    - devops-cloud-engineer-service
