---
- name: "It will save Load Balancer DNS name"
  hosts: management[0]
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
  tasks:
    - name: It will fetch the load balancer DNS nam
      shell: "./bin/kubectl get svc {{ ENVIRONMENT_NAME }}-service"
      register: loadbalancerdns
      args:
        chdir: $HOME

    - name: Copy the output to a local file
      copy:
        content: "{{ loadbalancerdns.stdout }}"
        dest: "~/loadbalancerdns.txt"
      delegate_to: localhost
